# Generated by Django 2.2.6 on 2019-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
