# Generated by Django 2.2.6 on 2019-10-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
